import type { Conversation } from '@/types/chat';

export const conversations: Conversation[] = [
  {
    id: 'c1',
    contactName: 'Amelia Hartman',
    avatarColor: '#004B87',
    initials: 'AH',
    lastMessage: 'Perfect, that works for me. See you then!',
    lastMessageTime: '09:41',
    unread: 2,
    online: true,
    status: 'Online',
    messages: [
      { id: 'm1', conversationId: 'c1', text: 'Hi! Is the onboarding session still on for tomorrow at 10?', sender: 'them', timestamp: '09:32' },
      { id: 'm2', conversationId: 'c1', text: 'Hi Amelia! Yes, 10 AM sharp. We will send over the agenda shortly.', sender: 'me', timestamp: '09:34', status: 'read' },
      { id: 'm3', conversationId: 'c1', text: 'Great, looking forward to it. Should I prepare anything beforehand?', sender: 'them', timestamp: '09:36' },
      { id: 'm4', conversationId: 'c1', text: 'Just bring your team list and any current workflow notes. We will handle the rest.', sender: 'me', timestamp: '09:38', status: 'read' },
      { id: 'm5', conversationId: 'c1', text: 'Perfect, that works for me. See you then!', sender: 'them', timestamp: '09:41' },
    ],
  },
  {
    id: 'c2',
    contactName: 'Marcus Lee',
    avatarColor: '#0E7C7B',
    initials: 'ML',
    lastMessage: 'Can you share the invoice for last month?',
    lastMessageTime: '08:52',
    unread: 1,
    online: false,
    status: 'Last seen 08:30',
    messages: [
      { id: 'm1', conversationId: 'c2', text: 'Morning! Quick question about billing.', sender: 'them', timestamp: '08:45' },
      { id: 'm2', conversationId: 'c2', text: 'Good morning Marcus! Sure, what do you need?', sender: 'me', timestamp: '08:47', status: 'read' },
      { id: 'm3', conversationId: 'c2', text: 'Can you share the invoice for last month?', sender: 'them', timestamp: '08:52' },
    ],
  },
  {
    id: 'c3',
    contactName: 'Priya Nair',
    avatarColor: '#B45309',
    initials: 'PN',
    lastMessage: 'Thanks for the quick turnaround!',
    lastMessageTime: 'Yesterday',
    unread: 0,
    online: true,
    status: 'Online',
    messages: [
      { id: 'm1', conversationId: 'c3', text: 'Hey, the new feature is not loading on my end.', sender: 'them', timestamp: '14:02' },
      { id: 'm2', conversationId: 'c3', text: 'Sorry about that. Can you share a screenshot?', sender: 'me', timestamp: '14:05', status: 'read' },
      { id: 'm3', conversationId: 'c3', text: 'Sure, sending it now.', sender: 'them', timestamp: '14:06' },
      { id: 'm4', conversationId: 'c3', text: 'Got it. Pushed a fix, should be live in a couple minutes.', sender: 'me', timestamp: '14:12', status: 'read' },
      { id: 'm5', conversationId: 'c3', text: 'Thanks for the quick turnaround!', sender: 'them', timestamp: '14:15' },
    ],
  },
  {
    id: 'c4',
    contactName: 'Tobias Werner',
    avatarColor: '#6B21A8',
    initials: 'TW',
    lastMessage: 'Let me check with the team and get back to you.',
    lastMessageTime: 'Yesterday',
    unread: 0,
    online: false,
    status: 'Last seen yesterday',
    messages: [
      { id: 'm1', conversationId: 'c4', text: 'Are there any discounts for annual plans?', sender: 'them', timestamp: '11:20' },
      { id: 'm2', conversationId: 'c4', text: 'We offer 15% off on annual subscriptions. Want me to set that up?', sender: 'me', timestamp: '11:24', status: 'read' },
      { id: 'm3', conversationId: 'c4', text: 'Let me check with the team and get back to you.', sender: 'them', timestamp: '11:30' },
    ],
  },
  {
    id: 'c5',
    contactName: 'Sofia Romano',
    avatarColor: '#BE123C',
    initials: 'SR',
    lastMessage: 'Got it, I will send the contract over today.',
    lastMessageTime: 'Mon',
    unread: 0,
    online: false,
    status: 'Last seen Monday',
    messages: [
      { id: 'm1', conversationId: 'c5', text: 'Hello! Following up on the partnership proposal.', sender: 'them', timestamp: '10:00' },
      { id: 'm2', conversationId: 'c5', text: 'Hi Sofia! Great to hear from you. What details do you need?', sender: 'me', timestamp: '10:05', status: 'read' },
      { id: 'm3', conversationId: 'c5', text: 'Mostly the revenue share terms and onboarding timeline.', sender: 'them', timestamp: '10:08' },
      { id: 'm4', conversationId: 'c5', text: 'I will prepare a summary and share it by end of day.', sender: 'me', timestamp: '10:12', status: 'read' },
      { id: 'm5', conversationId: 'c5', text: 'Got it, I will send the contract over today.', sender: 'them', timestamp: '10:15' },
    ],
  },
];
